/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IndexViewDialog.java
 *
 * Created on Feb 27, 2010, 6:55:44 PM
 */
package kwic.ui;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import kwic.index.CircularShifter;
import kwic.index.IndexList;
import kwic.index.IndexedString;
import kwic.index.InputReader;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author s1n
 */
public class IndexViewDialog extends javax.swing.JDialog {

   /** Creates new form IndexViewDialog */
   public IndexViewDialog(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jTable1 = new javax.swing.JTable();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jScrollPane2 = new javax.swing.JScrollPane();
      _inputRecordList = new javax.swing.JTable();
      jScrollPane3 = new javax.swing.JScrollPane();
      _indexRecordList = new javax.swing.JTable();

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      jTable1.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jTable1.setName("jTable1"); // NOI18N
      jScrollPane1.setViewportView(jTable1);

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setName("Form"); // NOI18N

      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(kwic.ui.Main.class).getContext().getResourceMap(IndexViewDialog.class);
      jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
      jButton1.setName("jButton1"); // NOI18N

      javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(kwic.ui.Main.class).getContext().getActionMap(IndexViewDialog.class, this);
      jButton2.setAction(actionMap.get("loadFile")); // NOI18N
      jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
      jButton2.setName("jButton2"); // NOI18N

      jScrollPane2.setName("jScrollPane2"); // NOI18N

      _inputRecordList.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null}
         },
         new String [] {
            "Index", "Shifted Input"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      _inputRecordList.setName("_inputRecordList"); // NOI18N
      jScrollPane2.setViewportView(_inputRecordList);

      jScrollPane3.setName("jScrollPane3"); // NOI18N

      _indexRecordList.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null}
         },
         new String [] {
            "Index", "Shifted Input"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      _indexRecordList.setName("_indexRecordList"); // NOI18N
      jScrollPane3.setViewportView(_indexRecordList);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addContainerGap(332, Short.MAX_VALUE)
                  .addComponent(jButton2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton1))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                     .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton1)
               .addComponent(jButton2))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      java.awt.EventQueue.invokeLater(new Runnable() {

         public void run() {
            IndexViewDialog dialog = new IndexViewDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

               public void windowClosing(java.awt.event.WindowEvent e) {
                  System.exit(0);
               }
            });
            dialog.setVisible(true);
         }
      });
   }

   @Action
   public Task loadFile() {
      return new LoadFileTask(org.jdesktop.application.Application.getInstance(kwic.ui.Main.class));
   }

   private class LoadFileTask extends org.jdesktop.application.Task<Object, Void> {

      LoadFileTask(org.jdesktop.application.Application app) {
         super(app);

         //bring up the file dialog to select a file
         JFileChooser fc = new JFileChooser();
         int returnVal = fc.showOpenDialog(IndexViewDialog.this);

         if (returnVal == JFileChooser.APPROVE_OPTION) {
            _file = fc.getSelectedFile();
         } else {
            _file = null;
         }
         dlminput = ((DefaultTableModel) IndexViewDialog.this._inputRecordList.getModel());
         dlmindex = ((DefaultTableModel) IndexViewDialog.this._indexRecordList.getModel());
      }

      @Override
      protected Object doInBackground() {
         InputReader ir = null;
         IndexedString si = null;
         //open the input file for reading
         try {
            //clear out everything to start fresh
            IndexViewDialog.this._index = new IndexList(new CircularShifter());
            ir = new InputReader(_file.toString());
            this.dlminput.setRowCount(0);
            this.dlmindex.setRowCount(0);
         } catch (FileNotFoundException ex) {
            Logger.getLogger(IndexViewDialog.class.getName()).log(Level.SEVERE, null, ex);
         }

         //read in the input, one IndexedString after the next
         do {
            try {
               si = ir.next();
            } catch (java.util.regex.PatternSyntaxException pse) {
               //FIXME could mark bad lines and then show them somewhere
               pse.printStackTrace();
               continue;
            }
            if (si == null) {
               break;
            }
            IndexViewDialog.this._index.add(si);
            this.dlminput.addRow(new Object[]{si.getIndex(), si.toString()});
         } while (true);

         //update the DataModel for the indexed data
         for (IndexedString sin : IndexViewDialog.this._index) {
            System.out.println(sin.toString());
            this.dlmindex.addRow(new Object[]{sin.getIndex(), sin.toString()});
         }
         try {
            ir.close();
         } catch (IOException ex) {
            Logger.getLogger(IndexViewDialog.class.getName()).log(Level.SEVERE, null, ex);
         }

         return IndexViewDialog.this._index;
      }

      @Override
      protected void succeeded(Object result) {
         IndexViewDialog.this._inputRecordList.setModel(dlminput);
         IndexViewDialog.this._indexRecordList.setModel(dlmindex);
      }
      private File _file;
      private DefaultTableModel dlmindex = null;
      private DefaultTableModel dlminput = null;
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTable _indexRecordList;
   private javax.swing.JTable _inputRecordList;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JTable jTable1;
   // End of variables declaration//GEN-END:variables

   private IndexList _index = null;
}
